# Meltano Configuration File
# 
# One-time workstation setup:
# > meltano install  # Install the plugins declared by the project
#
# Sample usage for end-to-end development:
# > meltano run el    # Run the job titled 'el' to extract and load data
# > meltano run t     # Run the job titled 't' to transform data
# > meltano run bi    # Build and serve the Evidence BI reports
#
# Repeat the same actions as above on "prod":
# > meltano --environment=prod run elt evidence:build

version: 1

jobs:
  # Sample usage: `meltano run el`, `meltano run t`, `meltano run el t`, `meltano run elt`
- name: el         # Extract and load the raw data
  tasks:
  - tap-parquet     target-duckdb
  - tap-csv         target-duckdb
- name: t          # Transform the raw data
  tasks:
  - dbt-duckdb:run
  - dbt-duckdb:test
- name: elt        # Extract, Load, and Transform
  tasks:
  - tap-parquet     target-duckdb
  - tap-csv         target-duckdb
  - dbt-duckdb:run
  - dbt-duckdb:test
- name: bi         # Launch the Evidence BI dev environment
  tasks:
  - evidence:dev
- name: bi-compile # Build BI reports and test for breakages
  tasks:
  - evidence:build-strict
- name: full-build # End-to-end build and test
  tasks:
  - tap-parquet     target-duckdb
  - tap-csv         target-duckdb
  - dbt-duckdb:run
  - dbt-duckdb:test
  - evidence:build-strict

default_environment: dev
environments:
- name: dev
  env:
    nyctaxi_DB_PATH: ${MELTANO_PROJECT_ROOT}/reports/nyctaxi.${MELTANO_ENVIRONMENT}-duckdb
    nyctaxi_DB_NAME: nyctaxi
    nyctaxi_RAW_SCHEMA: tap_nyctaxi
- name: staging
  env:
    nyctaxi_DB_PATH: ${MELTANO_PROJECT_ROOT}/reports/nyctaxi.${MELTANO_ENVIRONMENT}-duckdb
    nyctaxi_DB_NAME: nyctaxi
    nyctaxi_RAW_SCHEMA: tap_nyctaxi
- name: prod
  env:
    nyctaxi_DB_PATH: ${MELTANO_PROJECT_ROOT}/reports/nyctaxi.${MELTANO_ENVIRONMENT}-duckdb
    nyctaxi_DB_NAME: nyctaxi
    nyctaxi_RAW_SCHEMA: tap_nyctaxi

plugins:
  extractors:
  - name: tap-parquet
    namespace: tap_parquet
    variant: dataops-tk
    pip_url: git+https://github.com/dataops-tk/tap-parquet.git
    capabilities:
    - catalog
    - discover
  - name: tap-csv
    namespace: tap_csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    capabilities:
    - catalog
    - discover
    
  loaders:
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.4
    config:
      filepath: ${nyctaxi_DB_PATH}
  - name: target-parquet
    variant: estrategiahq
    pip_url: git+https://github.com/estrategiahq/target-parquet.git
  utilities:
  - name: dbt-duckdb
    variant: jwills
    pip_url: dbt-core~=1.4.5 dbt-duckdb~=1.4.0 git+https://github.com/meltano/dbt-ext.git@v0.1.0
    config:
      project_dir: ${MELTANO_PROJECT_ROOT}
      profiles_dir: ${MELTANO_PROJECT_ROOT}
      path: ${nyctaxi_DB_PATH}
  - name: evidence
    variant: meltanolabs
    pip_url: evidence-ext>=0.5
    commands:
      dev: dev
    config:
      home_dir: ${MELTANO_PROJECT_ROOT}/reports
      settings:
        duckdb:
          # filename: ${MELTANO_PROJECT_ROOT}/reports/${nyctaxi_DB_NAME}.${MELTANO_ENVIRONMENT}.duckdb
          filename: ${nyctaxi_DB_NAME}.${MELTANO_ENVIRONMENT}-duckdb
project_id: ff061732-bd27-4021-916f-e8f8b55fcf9d
