duckdb:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', './reports/jaffle_shop.duckdb') }}"
      database: "{{ env_var('JAFFLE_DB_NAME', 'jaffle_shop') }}"
      schema: analytics
      threads: 4
  target: dev
