duckdb:
  outputs:
    dev:
      type: duckdb
      path: "{{ var('jaffle_db_path') }}"
      database: "{{ var('jaffle_db_name') }}"
      schema: "{{ var('jaffle_target_schema') }}"
      threads: 4
  target: dev
