name: CI

on: [pull_request,push]

jobs:
  e2e-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pipx install meltano
      - run: meltano install
      - run: meltano run el
      - run: meltano invoke dbt:run
      - run: meltano invoke dbt:test
